# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='languages',
            new_name='language',
        ),
    ]
