# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20160603_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='styles',
            new_name='style',
        ),
    ]
